/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.navercorp.pinpoint.thrift.dto.command;


public enum TTokenResponseCode implements org.apache.thrift.TEnum {
  OK(200),
  BAD_REQUEST(400),
  UNAUTHORIZED(401),
  INTERNAL_SERVER_ERROR(500);

  private final int value;

  private TTokenResponseCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TTokenResponseCode findByValue(int value) { 
    switch (value) {
      case 200:
        return OK;
      case 400:
        return BAD_REQUEST;
      case 401:
        return UNAUTHORIZED;
      case 500:
        return INTERNAL_SERVER_ERROR;
      default:
        return null;
    }
  }
}
