/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.navercorp.pinpoint.thrift.dto.command;


public enum TTokenType implements org.apache.thrift.TEnum {
  ALL(0),
  SPAN(1),
  STAT(2),
  UNKNOWN(-1);

  private final int value;

  private TTokenType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TTokenType findByValue(int value) { 
    switch (value) {
      case 0:
        return ALL;
      case 1:
        return SPAN;
      case 2:
        return STAT;
      case -1:
        return UNKNOWN;
      default:
        return null;
    }
  }
}
