/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.navercorp.pinpoint.thrift.dto.flink;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2019-04-12")
public class TFSpanStatBatch implements org.apache.thrift.TBase<TFSpanStatBatch, TFSpanStatBatch._Fields>, java.io.Serializable, Cloneable, Comparable<TFSpanStatBatch> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TFSpanStatBatch");

  private static final org.apache.thrift.protocol.TField T_FSPAN_STAT_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("tFSpanStatList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TFSpanStatBatchStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TFSpanStatBatchTupleSchemeFactory();

  private java.util.List<TFSpanStat> tFSpanStatList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    T_FSPAN_STAT_LIST((short)1, "tFSpanStatList");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // T_FSPAN_STAT_LIST
          return T_FSPAN_STAT_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.T_FSPAN_STAT_LIST, new org.apache.thrift.meta_data.FieldMetaData("tFSpanStatList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TFSpanStat.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TFSpanStatBatch.class, metaDataMap);
  }

  public TFSpanStatBatch() {
  }

  public TFSpanStatBatch(
    java.util.List<TFSpanStat> tFSpanStatList)
  {
    this();
    this.tFSpanStatList = tFSpanStatList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TFSpanStatBatch(TFSpanStatBatch other) {
    if (other.isSetTFSpanStatList()) {
      java.util.List<TFSpanStat> __this__tFSpanStatList = new java.util.ArrayList<TFSpanStat>(other.tFSpanStatList.size());
      for (TFSpanStat other_element : other.tFSpanStatList) {
        __this__tFSpanStatList.add(new TFSpanStat(other_element));
      }
      this.tFSpanStatList = __this__tFSpanStatList;
    }
  }

  public TFSpanStatBatch deepCopy() {
    return new TFSpanStatBatch(this);
  }

  @Override
  public void clear() {
    this.tFSpanStatList = null;
  }

  public int getTFSpanStatListSize() {
    return (this.tFSpanStatList == null) ? 0 : this.tFSpanStatList.size();
  }

  public java.util.Iterator<TFSpanStat> getTFSpanStatListIterator() {
    return (this.tFSpanStatList == null) ? null : this.tFSpanStatList.iterator();
  }

  public void addToTFSpanStatList(TFSpanStat elem) {
    if (this.tFSpanStatList == null) {
      this.tFSpanStatList = new java.util.ArrayList<TFSpanStat>();
    }
    this.tFSpanStatList.add(elem);
  }

  public java.util.List<TFSpanStat> getTFSpanStatList() {
    return this.tFSpanStatList;
  }

  public void setTFSpanStatList(java.util.List<TFSpanStat> tFSpanStatList) {
    this.tFSpanStatList = tFSpanStatList;
  }

  public void unsetTFSpanStatList() {
    this.tFSpanStatList = null;
  }

  /** Returns true if field tFSpanStatList is set (has been assigned a value) and false otherwise */
  public boolean isSetTFSpanStatList() {
    return this.tFSpanStatList != null;
  }

  public void setTFSpanStatListIsSet(boolean value) {
    if (!value) {
      this.tFSpanStatList = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case T_FSPAN_STAT_LIST:
      if (value == null) {
        unsetTFSpanStatList();
      } else {
        setTFSpanStatList((java.util.List<TFSpanStat>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case T_FSPAN_STAT_LIST:
      return getTFSpanStatList();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case T_FSPAN_STAT_LIST:
      return isSetTFSpanStatList();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TFSpanStatBatch)
      return this.equals((TFSpanStatBatch)that);
    return false;
  }

  public boolean equals(TFSpanStatBatch that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_tFSpanStatList = true && this.isSetTFSpanStatList();
    boolean that_present_tFSpanStatList = true && that.isSetTFSpanStatList();
    if (this_present_tFSpanStatList || that_present_tFSpanStatList) {
      if (!(this_present_tFSpanStatList && that_present_tFSpanStatList))
        return false;
      if (!this.tFSpanStatList.equals(that.tFSpanStatList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTFSpanStatList()) ? 131071 : 524287);
    if (isSetTFSpanStatList())
      hashCode = hashCode * 8191 + tFSpanStatList.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TFSpanStatBatch other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTFSpanStatList()).compareTo(other.isSetTFSpanStatList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTFSpanStatList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tFSpanStatList, other.tFSpanStatList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TFSpanStatBatch(");
    boolean first = true;

    sb.append("tFSpanStatList:");
    if (this.tFSpanStatList == null) {
      sb.append("null");
    } else {
      sb.append(this.tFSpanStatList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TFSpanStatBatchStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TFSpanStatBatchStandardScheme getScheme() {
      return new TFSpanStatBatchStandardScheme();
    }
  }

  private static class TFSpanStatBatchStandardScheme extends org.apache.thrift.scheme.StandardScheme<TFSpanStatBatch> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TFSpanStatBatch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // T_FSPAN_STAT_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.tFSpanStatList = new java.util.ArrayList<TFSpanStat>(_list0.size);
                TFSpanStat _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new TFSpanStat();
                  _elem1.read(iprot);
                  struct.tFSpanStatList.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setTFSpanStatListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TFSpanStatBatch struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tFSpanStatList != null) {
        oprot.writeFieldBegin(T_FSPAN_STAT_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.tFSpanStatList.size()));
          for (TFSpanStat _iter3 : struct.tFSpanStatList)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TFSpanStatBatchTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TFSpanStatBatchTupleScheme getScheme() {
      return new TFSpanStatBatchTupleScheme();
    }
  }

  private static class TFSpanStatBatchTupleScheme extends org.apache.thrift.scheme.TupleScheme<TFSpanStatBatch> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TFSpanStatBatch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTFSpanStatList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTFSpanStatList()) {
        {
          oprot.writeI32(struct.tFSpanStatList.size());
          for (TFSpanStat _iter4 : struct.tFSpanStatList)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TFSpanStatBatch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.tFSpanStatList = new java.util.ArrayList<TFSpanStat>(_list5.size);
          TFSpanStat _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new TFSpanStat();
            _elem6.read(iprot);
            struct.tFSpanStatList.add(_elem6);
          }
        }
        struct.setTFSpanStatListIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

